// Generated by Selenium IDE
package hogwarts.webAuto.POM.testcase;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class SearchDemoTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        //System.setProperty("webdriver.firefox.marionette", "C:\\Windows\\System32\\geckodriver.exe");
        //firefox启动默认用户配置
//        ProfilesIni pi = new ProfilesIni();
//        FirefoxProfile profile = pi.getProfile("default");
//        driver = new FirefoxDriver( new FirefoxOptions().setProfile(profile));
        //chrome启动默认用户配置
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--user-data-dir=C:\\Users\\xuecheng.MAIKE51\\AppData\\Local\\Google\\Chrome\\User Data");
        driver = new ChromeDriver(chromeOptions);
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        driver.manage().window().maximize();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

    }

    @After
    public void tearDown() {
        try {
            Thread.sleep(10 * 1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.quit();
    }

    @Test
    public void searchDemo() {
        // Test name: SearchDemo
        // Step # | name | target | value | comment
        // 1 | open | / |  |
        driver.get("https://testerhome.com/");
        // 2 | setWindowSize | 2576x1056 |  |
        //driver.manage().window().setSize(new Dimension(2576,1056));
        // 3 | click | name=q |  |
        driver.findElement(By.name("q")).click();
        // 4 | type | name=q | 接口测试 |
        driver.findElement(By.name("q")).sendKeys("接口测试");
        // 5 | sendKeys | name=q | ${KEY_ENTER} |
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        // 6 | click | linkText=只看精华 |  |
        driver.findElement(By.linkText("只看精华")).click();
        // 7 | click | css=.result:nth-child(2) > .topic em |  |
        driver.findElement(By.cssSelector(".result:nth-child(2) > .topic em")).click();
        new Actions(driver).moveToElement(driver.findElement(By.id("replies"))).perform();

    }

    @Test
    public void getJindata(){
        driver.get("https://testerhome.com/topics/19350");
        driver.switchTo().frame(0);
        driver.switchTo().defaultContent();
//        new Actions(driver).moveToElement(driver.findElement(By.className("gd-icon-logo powered-logo"))).perform();
//        driver.findElement(By.partialLinkText("金数据提供技术支持")).click();
        //new Actions(driver).moveToElement(driver.findElement(By.name("抱歉！你访问的表单已停止收集数据"))).perform();
        //driver.findElement(By.partialLinkText("金数据提供技术支持")).click();
        //new Actions(driver).moveToElement(driver.findElement(By.partialLinkText("金数据"))).perform();
        new WebDriverWait(driver,5).until(ExpectedConditions.titleContains("金数据"));
        System.out.println(driver.findElement(By.partialLinkText("金数据提供技术支持")).getLocation());
        driver.findElement(By.partialLinkText("金数据提供技术支持")).click();
        System.out.println(driver.getWindowHandles().size());
        //driver.switchTo().window((String) driver.getWindowHandles().toArray()[1]);
        //driver.switchTo().window((String) driver.getWindowHandles().toArray()[0]);
    }
    @Test
    public void profileDefault(){
        driver.get("https://www.baidu.com/");
    }
}
